development:
  access_key_id: ""
  secret_access_key: ""
  bucket: "eu-petrescue-dev"

test:
  access_key_id: 
  secret_access_key: 
  bucket: 

production:
  access_key_id: ""
  secret_access_key: ""
  bucket: "eu-petrescue-dev"
